# Generated by Django 4.2.23 on 2025-11-18 21:23

import django.db.models.deletion
from django.db import migrations, models

import backend.utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("county", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=10)),
                ("place", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("street_number", models.CharField(max_length=10)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, help_text="the North coordinate", null=True
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, help_text="the East coordinate", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "db_table": "address",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("C", "Company"), ("P", "Person")], max_length=1
                    ),
                ),
                (
                    "tax_identification_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="company name", max_length=30, null=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("job_title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "id_card_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "preferred_communication_language",
                    models.CharField(
                        choices=[("GR", "Greek"), ("EN", "English")],
                        max_length=2,
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("MOB", "Mobile"),
                            ("HMP", "Home phone"),
                            ("WKP", "Work phone"),
                            ("EML", "Email"),
                            ("SMS", "SMS"),
                            ("VIB", "Viber"),
                            ("WHA", "What's up"),
                            ("TLG", "Telegram"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("email_consent", models.BooleanField(default=False)),
                ("phone_consent", models.BooleanField(default=False)),
                ("sms_consent", models.BooleanField(default=False)),
                ("marketing_consent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "contact",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("phone_prefix", models.CharField(max_length=15, null=True)),
                ("alpha_2", models.CharField(max_length=2, unique=True)),
                ("alpha_3", models.CharField(max_length=3, unique=True)),
                ("numeric", models.CharField(max_length=3, unique=True)),
                ("region", models.CharField(max_length=20)),
                ("sub_region", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "db_table": "country",
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "db_table": "document_type",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.EmailField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "email",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("M", "Mobile"), ("L", "Landline")], max_length=1
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.country"
                    ),
                ),
            ],
            options={
                "db_table": "phone",
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
                (
                    "phone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.phone"
                    ),
                ),
            ],
            options={
                "db_table": "contact_phone",
                "unique_together": {("contact", "phone")},
            },
        ),
        migrations.CreateModel(
            name="ContactImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
            ],
            options={
                "db_table": "contact_image",
            },
        ),
        migrations.CreateModel(
            name="ContactFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
            ],
            options={
                "db_table": "contact_file",
            },
        ),
        migrations.CreateModel(
            name="ContactEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEO", "CEO"),
                            ("BRD", "Board member"),
                            ("DRC", "Director"),
                            ("MNG", "Manager"),
                            ("SLS", "Sales"),
                            ("OTH", "Other"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"type": "P"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_employers",
                        to="common.contact",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        limit_choices_to={"type": "C"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_employees",
                        to="common.contact",
                    ),
                ),
            ],
            options={
                "db_table": "contact_employee",
                "unique_together": {("employer", "employee")},
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="common.email"
                    ),
                ),
            ],
            options={
                "db_table": "contact_email",
                "unique_together": {("contact", "email")},
            },
        ),
        migrations.CreateModel(
            name="ContactDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRV", "Private agreement document"),
                            ("CNT", "Contract document"),
                            ("BNK", "Bank document"),
                            ("CLN", "Client portal document"),
                            ("ADV", "Advertisement"),
                            ("BLL", "Bill"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("issuer", models.CharField(max_length=100)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
            ],
            options={
                "db_table": "contact_document",
            },
        ),
        migrations.CreateModel(
            name="ContactAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=30)),
                ("postal_code", models.CharField(max_length=10)),
                ("street", models.CharField(max_length=50)),
                ("street_number", models.CharField(max_length=10)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="common.contact",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Addresses",
                "db_table": "contact_address",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="country_of_residence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.email",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="employees",
            field=models.ManyToManyField(
                through="common.ContactEmployee", to="common.contact"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="extra_emails",
            field=models.ManyToManyField(
                related_name="contacts",
                through="common.ContactEmail",
                to="common.email",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="extra_phones",
            field=models.ManyToManyField(
                related_name="contacts",
                through="common.ContactPhone",
                to="common.phone",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nationals",
                to="common.country",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.phone",
            ),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.country"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
                "db_table": "city",
            },
        ),
    ]
