# Generated by Django 4.2.23 on 2025-11-18 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import backend.utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COS", "Contract of Sale"),
                            ("TEN", "Tenancy Agreement"),
                            ("PMG", "Property management Agreement"),
                        ],
                        help_text="type after creation gets locked",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPN", "Open"),
                            ("RSV", "Reserved"),
                            ("CNL", "Cancelled"),
                            ("AGR", "Agreed"),
                        ],
                        help_text="After setting to Agreed or Cancelled, <br>the Agreement gets locked and cannot be edited",
                        max_length=3,
                    ),
                ),
                (
                    "agreement_signing_date",
                    models.DateField(
                        blank=True,
                        help_text="If a date is provided, the agreement will be thought as accepted. <br>This will lock the agreement for edit.",
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("cancel_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, default="")),
                ("private_agreement_date", models.DateField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                ("reservation_date", models.DateField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agreement",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "distance_from_airport",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_university",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_beach",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_hospital",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_shops",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_tube_station",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_rail_station",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_center",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_school",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(choices=[("CON", "Construction")], max_length=3),
                ),
                (
                    "construction_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFF", "Off plan"),
                            ("CON", "Under construction"),
                            ("STL", "Stalled"),
                            ("CMP", "Completed"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "energy_efficiency_grade",
                    models.CharField(
                        choices=[
                            ("PEN", "Pending certification"),
                            ("NRQ", "Not required"),
                            ("A", "A"),
                            ("AA", "A+"),
                            ("B", "B"),
                            ("BB", "B+"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("G", "G"),
                            ("H", "H"),
                        ],
                        max_length=3,
                    ),
                ),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "number_of_units",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("location_description", models.TextField(blank=True, default="")),
                ("amentities_description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "starting_price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                ("comments", models.JSONField(blank=True, default=list)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="common.address",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "real_estate_project",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                (
                    "distance_from_airport",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_university",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_beach",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_hospital",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_shops",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_tube_station",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_rail_station",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_center",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "distance_from_school",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PND", "Pending"),
                            ("AVL", "Available"),
                            ("RSV", "Reserved"),
                            ("SLD", "Sold"),
                            ("RNT", "Rented"),
                            ("WTH", "Withdrawn"),
                            ("OFF", "Under offer"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "utilization",
                    models.CharField(
                        choices=[
                            ("SL", "Sale"),
                            ("RNT", "Rent"),
                            ("SNR", "Sale and Rent"),
                            ("MNG", "Manage"),
                            ("AUC", "Auction"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="English only", max_length=100, unique=True
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, default="", help_text="English only", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="English only"),
                ),
                ("inherit_project_media", models.BooleanField(default=False)),
                (
                    "unit_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "list_selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "list_rental_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "construction_year",
                    models.IntegerField(
                        blank=True,
                        help_text="If not construction complete, this is estimated year",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900,
                                message="This value must be greater to or equal than 1900",
                            ),
                            django.core.validators.MaxValueValidator(
                                2060,
                                message="This value must be smaller to or equal than 2060",
                            ),
                        ],
                    ),
                ),
                (
                    "construction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CNR", "Concrete"),
                            ("PFB", "Prefabricated"),
                            ("MTL", "Metal"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "construction_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFF", "Off plan"),
                            ("CON", "Under construction"),
                            ("UNF", "Unfinished"),
                            ("CMP", "Complete"),
                            ("RSL", "Resale"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "renovation_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Greater than construction year.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900,
                                message="This value must be greater to or equal than 1900",
                            ),
                            django.core.validators.MaxValueValidator(
                                2060,
                                message="This value must be smaller to or equal than 2060",
                            ),
                        ],
                    ),
                ),
                ("floor", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "building_floors",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "parking_spots",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "covered_parking_spots",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "uncovered_parking_spots",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "customer_parking_spots",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "energy_efficiency_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEN", "Pending certification"),
                            ("NRQ", "Not required"),
                            ("A", "A"),
                            ("AA", "A+"),
                            ("B", "B"),
                            ("BB", "B+"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("G", "G"),
                            ("H", "H"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "electricity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SP", "Single phase"),
                            ("TP", "Three phase"),
                            ("IN", "Industrial"),
                            ("NA", "Unavailable"),
                        ],
                        default="NA",
                        max_length=3,
                    ),
                ),
                (
                    "heating_type",
                    models.CharField(
                        blank=True,
                        choices=[("AUT", "Autonomous"), ("CNT", "Central")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "heating_medium",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PTR", "Petrol"),
                            ("GS", "Gas"),
                            ("BGS", "Bottle Gas-LPG"),
                            ("EL", "Electric"),
                            ("UFL", "Underfloor"),
                            ("STR", "Storage"),
                            ("HPM", "Heat pump"),
                            ("GTH", "Geothermal"),
                            ("FCL", "Fan coil"),
                            ("SLR", "Solar"),
                            ("OIL", "Oil"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cooling_type",
                    models.CharField(
                        blank=True,
                        choices=[("AUT", "Autonomous"), ("CNT", "Central")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "office_spaces",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "awnings",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAN", "Manual"),
                            ("EL", "Electric"),
                            ("NA", "Non available"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "floor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAR", "Marble"),
                            ("TIL", "Tiles"),
                            ("WDN", "Wooden floor"),
                            ("GRN", "Granite"),
                            ("IND", "Industrial"),
                            ("MOS", "Mosaic"),
                            ("LAM", "Laminate"),
                            ("PAR", "Parquet"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "furnished",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUL", "Fully"),
                            ("PAR", "Partially"),
                            ("OPT", "Optionally"),
                            ("NO", "Unfurnished"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "kitchen_type",
                    models.CharField(
                        blank=True,
                        choices=[("OPP", "Open plan"), ("SEP", "Seperated")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "office_layout",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OP", "Open plan"),
                            ("PRT", "Partitioned"),
                            ("SHC", "Shell and core"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "town_planning_zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RES", "Residential"),
                            ("COM", "Commercial"),
                            ("IND", "Industrial"),
                            ("AGR", "Agricultural"),
                            ("TRS", "Tourist"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cover_factor",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "building_density",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                ("ideal_for", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "licensed_for",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("comments", models.JSONField(blank=True, default=list)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.address",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "db_table": "property",
            },
        ),
        migrations.CreateModel(
            name="PropertyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Property category",
                "verbose_name_plural": "Property categories",
                "db_table": "property_category",
            },
        ),
        migrations.CreateModel(
            name="RelatedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("BLC", "Blocked by"),
                            ("EXT", "Extends"),
                            ("CHL", "Child"),
                        ],
                        max_length=3,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.project",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_project",
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "db_table": "related_project",
                "unique_together": {("project", "related_project")},
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.propertycategory",
                    ),
                ),
            ],
            options={
                "db_table": "property_type",
            },
        ),
        migrations.CreateModel(
            name="PropertyOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "percentage",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            ),
                            django.core.validators.MaxValueValidator(
                                1,
                                message="This value must be smaller to or equal than 1",
                            ),
                        ]
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties_ownerships",
                        to="common.contact",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_owners",
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_owner",
                "unique_together": {("property", "owner")},
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_image",
            },
        ),
        migrations.CreateModel(
            name="PropertyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_file",
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRV", "Private agreement document"),
                            ("CNT", "Contract document"),
                            ("BNK", "Bank document"),
                            ("CLN", "Client portal document"),
                            ("ADV", "Advertisement"),
                            ("BLL", "Bill"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("issuer", models.CharField(max_length=100)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_document",
            },
        ),
        migrations.CreateModel(
            name="PropertyAssociatedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_associated_contact",
                "unique_together": {("property", "contact")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="associated_contacts",
            field=models.ManyToManyField(
                related_name="associated_properties",
                through="real_estate.PropertyAssociatedContact",
                to="common.contact",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="owners",
            field=models.ManyToManyField(
                related_name="owner_properties",
                through="real_estate.PropertyOwner",
                to="common.contact",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="real_estate.project",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="real_estate.propertytype",
            ),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_image",
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_file",
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRV", "Private agreement document"),
                            ("CNT", "Contract document"),
                            ("BNK", "Bank document"),
                            ("CLN", "Client portal document"),
                            ("ADV", "Advertisement"),
                            ("BLL", "Bill"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("issuer", models.CharField(max_length=100)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_document",
            },
        ),
        migrations.CreateModel(
            name="ProjectContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.contact"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_contact",
                "unique_together": {("project", "contact")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.address"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Addresses",
                "db_table": "project_address",
                "unique_together": {("project", "address")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="extra_addresses",
            field=models.ManyToManyField(
                related_name="related_projects",
                through="real_estate.ProjectAddress",
                to="common.address",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="related_contacts",
            field=models.ManyToManyField(
                related_name="projects",
                through="real_estate.ProjectContact",
                to="common.contact",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="related_projects",
            field=models.ManyToManyField(
                through="real_estate.RelatedProject", to="real_estate.project"
            ),
        ),
        migrations.CreateModel(
            name="AgreementRelatedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("LAW", "Lawyer"),
                            ("LWF", "Lawyer firm"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.agreement",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.contact"
                    ),
                ),
            ],
            options={
                "db_table": "agreement_related_contact",
                "unique_together": {("agreement", "contact")},
            },
        ),
        migrations.CreateModel(
            name="AgreementParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("BUY", "Buyer"),
                            ("SLR", "Seller"),
                            ("LND", "Landlord"),
                            ("TNT", "Tenant"),
                            ("MNG", "Manager"),
                            ("RPR", "Representative"),
                            ("LWR", "Lawyer"),
                        ],
                        max_length=3,
                    ),
                ),
                ("signature_requirement", models.BooleanField(default=False)),
                (
                    "percentage_ownership",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            ),
                            django.core.validators.MaxValueValidator(
                                1,
                                message="This value must be smaller to or equal than 1",
                            ),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("accepted", models.BooleanField(default=False)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_parties",
                        to="real_estate.agreement",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="involved_agreements",
                        to="common.contact",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agreement Parties",
                "db_table": "agreement_party",
                "unique_together": {("agreement", "party")},
            },
        ),
        migrations.CreateModel(
            name="AgreementDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("issuer", models.CharField(max_length=100)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRV", "Private agreement document"),
                            ("CNT", "Contract document"),
                            ("BNK", "Bank document"),
                            ("CLN", "Client portal document"),
                            ("OTH", "Other"),
                        ],
                        default="PRV",
                        max_length=3,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.agreement",
                    ),
                ),
            ],
            options={
                "db_table": "agreement_document",
            },
        ),
        migrations.CreateModel(
            name="AgreementCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="This value must be positive."
                            )
                        ],
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="real_estate.agreement",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.contact"
                    ),
                ),
            ],
            options={
                "db_table": "agreement_commission",
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="parties",
            field=models.ManyToManyField(
                related_name="party_agreements",
                through="real_estate.AgreementParty",
                to="common.contact",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="real_estate.project",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="real_estate.property",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="related_contacts",
            field=models.ManyToManyField(
                related_name="related_agreements",
                through="real_estate.AgreementRelatedContact",
                to="common.contact",
            ),
        ),
    ]
