# Generated by Django 4.2.23 on 2025-11-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementcommission",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="real_estate.agreement",
            ),
        ),
    ]
