# Generated by Django 4.2.23 on 2025-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0002_alter_agreementcommission_agreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="agreement_int",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="closure_percentage",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="has_private_agreement",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="unique_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
