# Generated by Django 4.2.23 on 2025-11-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "real_estate",
            "0003_agreement_agreement_int_agreement_closure_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="signing_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
