# Generated by Django 4.2.23 on 2025-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0004_agreement_signing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="agreement_int",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="closure_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
