# Generated by Django 4.2.23 on 2025-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0005_alter_agreement_agreement_int_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="agreement_int",
            field=models.IntegerField(
                blank=True, default=1, help_text="needed an integer field", null=True
            ),
        ),
    ]
