# Generated by Django 4.2.23 on 2025-12-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0006_alter_agreement_agreement_int"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreementcommission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="agreementcommission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
