# Generated by Django 4.2.23 on 2025-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0007_agreementcommission_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyassociatedcontact",
            options={"verbose_name": "Property Contact"},
        ),
        migrations.AlterModelOptions(
            name="propertyowner",
            options={"verbose_name": "Property Owner"},
        ),
    ]
