# Generated by Django 4.2.23 on 2026-01-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0008_alter_propertyassociatedcontact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="expected_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
