# Generated by Django 4.2.23 on 2026-01-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("real_estate", "0009_project_expected_completion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="expected_completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
