# Generated by Django 4.2.23 on 2025-11-18 21:23

from django.db import migrations, models

import backend.utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("identifier", models.CharField(max_length=50)),
                ("issuer", models.CharField(blank=True, default="", max_length=50)),
                ("issued_at", models.DateField(blank=True, null=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "document",
            },
        ),
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", max_length=300)),
            ],
            options={
                "verbose_name_plural": "Document file",
                "db_table": "document_file",
            },
        ),
        migrations.CreateModel(
            name="DocumentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "img",
                    models.ImageField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", max_length=300)),
            ],
            options={
                "verbose_name_plural": "Document image",
                "db_table": "document_image",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "file",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "img",
                    models.ImageField(
                        max_length=255,
                        upload_to=backend.utils.files.get_file_upload_path,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "image",
            },
        ),
    ]
